#!name=Spotify
#!desc=Spotify Unlock
#!For: https://github.com/app2smile/rules/blob/master/module/spotify.module

[Header Rewrite]
# if-none-match返回304状态码
http-request ^https:\/\/spclient\.wg\.spotify\.com\/user-customization-service\/v1\/customize$ header-del if-none-match

[Script]
spotify-json = type=http-request,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(artistview\/v1\/artist|album-entity-view\/v2\/album)\/,requires-body=0,script-path=https://raw.githubusercontent.com/iuu666/Backup/main/js/Spotify/spotify-json.js
spotify-proto = type=http-response,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,requires-body=1,binary-body-mode=1,max-size=0,script-path=https://raw.githubusercontent.com/iuu666/Backup/main/js/Spotify/spotify-proto.js,script-update-interval=0

[MITM]
hostname = %APPEND% spclient.wg.spotify.com
