name: Update List

on:
  push:  # 在代码推送到仓库时触发
  workflow_dispatch:  # 允许手动触发此工作流
  schedule:
    - cron: "00 00 * * *"  # 每天 UTC 时间 00:00 自动触发

permissions:
  contents: write  # 允许写入仓库内容

jobs:
  build:
    runs-on: ubuntu-latest  # 在最新版本的 Ubuntu 环境中运行

    steps:
      - uses: actions/checkout@v3  # 检出代码仓库
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8  # 设置 Python 版本为 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # 升级 pip
          pip install requests lxml  # 安装 requests 和 lxml 库
      - name: Run Python
        run: |
          python scripts/BM7Surge.py 
          python scripts/BM7QuanX.py
          python scripts/LS.py
          python scripts/vc.py

      - uses: stefanzweifel/git-auto-commit-action@v5  # 使用 git-auto-commit-action 自动提交更改
        with:
          commit_message: Update List
