name: Run Proxy Fetch Script

# 定义何时触发工作流
on:
  # 每天 UTC 时间 23:00 自动触发工作流
  schedule:
    - cron: '0 23 * * *'
  # 手动触发工作流
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # Step 1: 检出代码库
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # 使用3.x版本的Python，可以根据需求调整

    # Step 3: 安装依赖
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests lxml

    # Step 4: 运行 Python 脚本
    - name: Run Proxy_All_No_Resolve script
      run: python scripts/Proxy_All_No_Resolve.py
